services:
  pricetracker-db:
    image: mongo:latest
    container_name: pricetracker-db 
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: pricetracker
    volumes:
      - pricetracker-data:/data/db

volumes:
  pricetracker-data: