services:
  pricetracker-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pricetracker-app
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - pricetracker-db
    environment:
      - MONGO_URI=mongodb://mongo:mongo@pricetracker-db:27017/
      - MONGO_DB=pricetracker
      - APP_HOST=0.0.0.0
      - JWT_SECRET=${JWT_SECRET:-supersecretkey}
      - JWT_ALGORITHM=HS256
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@pricetracker.com}
      - SMTP_SERVER=${SMTP_SERVER:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME:-}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-}
      - SENDER_EMAIL=${SENDER_EMAIL:-noreply@pricetracker.com}
    volumes:
      - ./backend/logs:/app/backend/logs
  
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports: 
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: pricetracker-db
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
    depends_on:
      - pricetracker-db
  
  pricetracker-db:
    image: mongo:latest
    container_name: pricetracker-db 
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: pricetracker
    volumes:
      - pricetracker-data:/data/db

volumes:
  pricetracker-data: